sudo: false
language: node_js
node_js:
  - "8.3"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script: 'true'
notifications:
  email:
    recipients:
      - bruno@logerfo.com.br
    on_success: never # default: change
    on_failure: always
