name: close-label
description: A Probot app that applies a specific label to an issue closed through a pull request considering its current labels.
author: Bruno Logerfo

branding:
  icon: git-pull-request
  color: red

runs:
  using: docker
  image: Dockerfile

inputs:
  repo-token:
    description: You probably want it to be secrets.GITHUB_TOKEN
    required: true
